insert into book_details (shelf, user_rating, book_id, user_id) values (1, 8, 1, 1);
insert into book_details (shelf, user_rating, book_id, user_id) values (1, 9, 2, 1);
insert into book_details (shelf, book_id, user_id) values (2, 3, 1);
insert into book_details (shelf, user_rating, book_id, user_id) values (3, 9, 5, 1);
insert into book_details (shelf, user_rating, book_id, user_id) values (1, 7, 1, 2);
insert into book_details (shelf, user_rating, book_id, user_id) values (1, 8, 2, 2);
insert into book_details (shelf, user_rating, book_id, user_id) values (4, 7, 3, 2);
insert into book_details (shelf, user_rating, book_id, user_id) values (4, 8, 4, 2);
insert into book_details (shelf, user_rating, book_id, user_id) values (4, 8, 5, 2);
insert into book_details (shelf, user_rating, book_id, user_id) values (1, 8, 1, 3);
insert into book_details (shelf, user_rating, book_id, user_id) values (1, 8, 2, 3);
insert into book_details (shelf, user_rating, book_id, user_id) values (1, 8, 3, 3);
insert into book_details (shelf, user_rating, book_id, user_id) values (1, 8, 4, 3);
insert into book_details (shelf, user_rating, book_id, user_id) values (1, 8, 5, 3);
insert into book_details (shelf, user_rating, book_id, user_id) values (1, 8, 6, 3);
insert into book_details (shelf, user_rating, book_id, user_id) values (1, 8, 7, 3);
insert into book_details (shelf, user_rating, book_id, user_id) values (1, 8, 8, 3);
insert into reader_books_details(user_id, books_details_id) VALUES (1,1);
insert into reader_books_details(user_id, books_details_id) VALUES (1,2);
insert into reader_books_details(user_id, books_details_id) VALUES (1,3);
insert into reader_books_details(user_id, books_details_id) VALUES (1,4);
insert into reader_books_details(user_id, books_details_id) VALUES (2,5);
insert into reader_books_details(user_id, books_details_id) VALUES (2,6);
insert into reader_books_details(user_id, books_details_id) VALUES (2,7);
insert into reader_books_details(user_id, books_details_id) VALUES (2,8);
insert into reader_books_details(user_id, books_details_id) VALUES (2,9);
insert into reader_books_details(user_id, books_details_id) VALUES (3,10);
insert into reader_books_details(user_id, books_details_id) VALUES (3,11);
insert into reader_books_details(user_id, books_details_id) VALUES (3,12);
insert into reader_books_details(user_id, books_details_id) VALUES (3,13);
insert into reader_books_details(user_id, books_details_id) VALUES (3,14);
insert into reader_books_details(user_id, books_details_id) VALUES (3,15);
insert into reader_books_details(user_id, books_details_id) VALUES (3,16);
insert into reader_books_details(user_id, books_details_id) VALUES (3,17);